#!/bin/bash
#SBATCH --partition normal
#SBATCH --mem-per-cpu 4G
#SBATCH -c 1
#SBATCH -t 12:00:00

source activate base

python /home/sarahe/HybPiper/get_seq_lengths.py /home/sarahe/GitHub/BSc/test_target_file_single.fasta /home/sarahe/GitHub/BSc/names.txt dna > test_seq_lengths.txt