#!/bin/bash
#SBATCH --partition normal
#SBATCH --mem-per-cpu 4G
#SBATCH -c 1
#SBATCH -t 12:00:00

source activate base

while read name; 
do /home/sarahe/HybPiper/reads_first.py -b /home/sarahe/GitHub/BSc/test_target_file -r $name*.fastq --prefix $name --bwa
done < /home/sarahe/GitHub/BSc/names.txt